/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as JobRouteRouteImport } from './routes/_job/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTestRouteImport } from './routes/api/test'
import { Route as ApiSecondRouteImport } from './routes/api/second'
import { Route as ApiRecommendationRouteImport } from './routes/api/recommendation'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as JobPortalIndexRouteImport } from './routes/_job/portal/index'
import { Route as ApiGetdataIdRouteImport } from './routes/api/getdata.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as JobPortalCreateRouteImport } from './routes/_job/portal/create'
import { Route as JobPortalIdRouteImport } from './routes/_job/portal/$id'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const JobRouteRoute = JobRouteRouteImport.update({
  id: '/_job',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestRoute = ApiTestRouteImport.update({
  id: '/api/test',
  path: '/api/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSecondRoute = ApiSecondRouteImport.update({
  id: '/api/second',
  path: '/api/second',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecommendationRoute = ApiRecommendationRouteImport.update({
  id: '/api/recommendation',
  path: '/api/recommendation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const JobPortalIndexRoute = JobPortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => JobRouteRoute,
} as any)
const ApiGetdataIdRoute = ApiGetdataIdRouteImport.update({
  id: '/api/getdata/$id',
  path: '/api/getdata/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const JobPortalCreateRoute = JobPortalCreateRouteImport.update({
  id: '/portal/create',
  path: '/portal/create',
  getParentRoute: () => JobRouteRoute,
} as any)
const JobPortalIdRoute = JobPortalIdRouteImport.update({
  id: '/portal/$id',
  path: '/portal/$id',
  getParentRoute: () => JobRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/api/recommendation': typeof ApiRecommendationRoute
  '/api/second': typeof ApiSecondRoute
  '/api/test': typeof ApiTestRoute
  '/portal/$id': typeof JobPortalIdRoute
  '/portal/create': typeof JobPortalCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/getdata/$id': typeof ApiGetdataIdRoute
  '/portal/': typeof JobPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/api/recommendation': typeof ApiRecommendationRoute
  '/api/second': typeof ApiSecondRoute
  '/api/test': typeof ApiTestRoute
  '/portal/$id': typeof JobPortalIdRoute
  '/portal/create': typeof JobPortalCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/getdata/$id': typeof ApiGetdataIdRoute
  '/portal': typeof JobPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_job': typeof JobRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/api/recommendation': typeof ApiRecommendationRoute
  '/api/second': typeof ApiSecondRoute
  '/api/test': typeof ApiTestRoute
  '/_job/portal/$id': typeof JobPortalIdRoute
  '/_job/portal/create': typeof JobPortalCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/getdata/$id': typeof ApiGetdataIdRoute
  '/_job/portal/': typeof JobPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/api/recommendation'
    | '/api/second'
    | '/api/test'
    | '/portal/$id'
    | '/portal/create'
    | '/api/auth/$'
    | '/api/getdata/$id'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/api/recommendation'
    | '/api/second'
    | '/api/test'
    | '/portal/$id'
    | '/portal/create'
    | '/api/auth/$'
    | '/api/getdata/$id'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_job'
    | '/about'
    | '/_auth/login'
    | '/_auth/signup'
    | '/api/recommendation'
    | '/api/second'
    | '/api/test'
    | '/_job/portal/$id'
    | '/_job/portal/create'
    | '/api/auth/$'
    | '/api/getdata/$id'
    | '/_job/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  JobRouteRoute: typeof JobRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ApiRecommendationRoute: typeof ApiRecommendationRoute
  ApiSecondRoute: typeof ApiSecondRoute
  ApiTestRoute: typeof ApiTestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGetdataIdRoute: typeof ApiGetdataIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_job': {
      id: '/_job'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof JobRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test': {
      id: '/api/test'
      path: '/api/test'
      fullPath: '/api/test'
      preLoaderRoute: typeof ApiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/second': {
      id: '/api/second'
      path: '/api/second'
      fullPath: '/api/second'
      preLoaderRoute: typeof ApiSecondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recommendation': {
      id: '/api/recommendation'
      path: '/api/recommendation'
      fullPath: '/api/recommendation'
      preLoaderRoute: typeof ApiRecommendationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_job/portal/': {
      id: '/_job/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof JobPortalIndexRouteImport
      parentRoute: typeof JobRouteRoute
    }
    '/api/getdata/$id': {
      id: '/api/getdata/$id'
      path: '/api/getdata/$id'
      fullPath: '/api/getdata/$id'
      preLoaderRoute: typeof ApiGetdataIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_job/portal/create': {
      id: '/_job/portal/create'
      path: '/portal/create'
      fullPath: '/portal/create'
      preLoaderRoute: typeof JobPortalCreateRouteImport
      parentRoute: typeof JobRouteRoute
    }
    '/_job/portal/$id': {
      id: '/_job/portal/$id'
      path: '/portal/$id'
      fullPath: '/portal/$id'
      preLoaderRoute: typeof JobPortalIdRouteImport
      parentRoute: typeof JobRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface JobRouteRouteChildren {
  JobPortalIdRoute: typeof JobPortalIdRoute
  JobPortalCreateRoute: typeof JobPortalCreateRoute
  JobPortalIndexRoute: typeof JobPortalIndexRoute
}

const JobRouteRouteChildren: JobRouteRouteChildren = {
  JobPortalIdRoute: JobPortalIdRoute,
  JobPortalCreateRoute: JobPortalCreateRoute,
  JobPortalIndexRoute: JobPortalIndexRoute,
}

const JobRouteRouteWithChildren = JobRouteRoute._addFileChildren(
  JobRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  JobRouteRoute: JobRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ApiRecommendationRoute: ApiRecommendationRoute,
  ApiSecondRoute: ApiSecondRoute,
  ApiTestRoute: ApiTestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGetdataIdRoute: ApiGetdataIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
